CREATE DATABASE IF NOT EXISTS ARCHIVOS;
CREATE DATABASE IF NOT EXISTS INVENTARIO;
CREATE DATABASE IF NOT EXISTS FACTURACION;
CREATE DATABASE IF NOT EXISTS TENANT;
GRANT ALL PRIVILEGES ON ARCHIVOS.* TO 'paul'@'%';
GRANT ALL PRIVILEGES ON INVENTARIO.* TO 'paul'@'%';
GRANT ALL PRIVILEGES ON FACTURACION.* TO 'paul'@'%';
GRANT ALL PRIVILEGES ON TENANT.* TO 'paul'@'%';
FLUSH PRIVILEGES;